name: publish-technical-documentation-next

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - "docs/sources/**"
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/tempo'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/publish-technical-documentation@6cdd2c6054b487ea8b5c0c284225fcd35f97eaa7
        with:
          source_directory: docs/sources/tempo
          website_directory: content/docs/tempo/next
      - uses: grafana/writers-toolkit/publish-technical-documentation@6cdd2c6054b487ea8b5c0c284225fcd35f97eaa7
        with:
          source_directory: docs/sources/helm-charts/tempo-distributed
          website_directory: content/docs/helm-charts/tempo-distributed/next
