name: Update `make docs` procedure

permissions: {}

on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
jobs:
  main:
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/update-make-docs@6cdd2c6054b487ea8b5c0c284225fcd35f97eaa7
