name: Update `make docs` procedure

permissions: {}

on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
jobs:
  main:
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/update-make-docs@0a0f604924aaf2b23e93943616370e51946885b8
